import React from 'react';
import ReactDOM from 'react-dom';
import App from './movie/App';

ReactDOM.render(<App />, document.getElementById('root'));

// import './example/jsx-1.js'
// import './example/jsx-2.js'
// import './example/jsx-3-also-expression.js'
// import './example/jsx-4-attributes.js'
// import './example/render-1.js'
// import './example/component-1.js'
// import './example/component-2.js'
// import './example/component-3.js'
// import './example/component-4-refactor.js'
// import './example/component-5-convert.js'
// import './example/state-1.js'
// import './example/state-2.js'
// import './example/state-3-usage.js'
// import './example/state-4-update.js'
// import './example/event-1.js'
// import './example/event-2-this.js'
// import './example/event-3-class-field.js'
// import './example/event-4-poor-arrow.js'
// import './example/condition-1.js'
// import './example/condition-2-with-var.js'
// import './example/condition-3-inline-if.js'
// import './example/condition-4-inline-if-else.js'
// import './example/prevent-rendering.js'
// import './example/list-and-key-1.js'
// import './example/list-and-key-2-warning.js'
// import './example/list-and-key-3-fix.js'
// import './example/list-and-key-4-incorrect.js'
// import './example/list-and-key-5-correct.js'
// import './example/form-1-uncontrolled.js'
// import './example/form-2-controlled-input.js'
// import './example/form-3-controlled-text-area.js'
// import './example/form-4-controlled-select.js'
// import './example/form-5-null.js'
// import './example/prop-type-1.js'